### ISSUE TITLE
Error on open Aerojump

### ISSUE THREAD

**Issue by henryoliver** [philip-karlsson/aerojump.nvim#13]
I can't launch the plugin, maybe the error still exists.

_NVIM v0.4.3_

init.vim
```
Plug 'ripxorip/aerojump.nvim', { 'do': ':UpdateRemotePlugins' }
```

```
Error detected while processing function remote#define#request:
line    2:
Error invoking '/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump:command:Aerojump' on channel 4 (python3-rplugin-host):
error caught in request handler '/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump:command:Aerojump [[], [90, 90]]':
Traceback (most recent call last):
  File "/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump/__init__.py", line 229, in Aerojump
    settings['input'] = args[0]
IndexError: list index out of range
Press ENTER or type command to continue
```

Thanks!

**Comment by ripxorip** [comment]
Hi! I think you are missing a parameter when starting the plugin. Whats the command you are using to summon the plugin?

**Comment by henryoliver** [comment]
Hi @ripxorip, I just installed the plugin and later I did `: Aerojump`

```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
Error invoking '/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump:command:Aerojump' on channel 4 (python3-rplugin-host):
error caught in request handler '/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump:command:Aerojump [[], [1, 1]]':
Traceback (most recent call last):
  File "/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump/__init__.py", line 229, in Aerojump
    settings['input'] = args[0]
IndexError: list index out of range
Press ENTER or type command to continue
```

The only way that seems to work is if I use mapping keys on my vimrc: 
`nmap <Leader>as <Plug>(AerojumpSpace)`
but even with that, does not seems to work on find words and I'm getting this other error after typing:
```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
Error invoking '/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump:command:AerojumpUp' on channel 4 (python3-rplugin-host):
error caught in request handler '/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump:command:AerojumpUp [[], [4, 4]]':
Traceback (most recent call last):
  File "/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump/__init__.py", line 314, in AerojumpUp
    self.__update_highlights(self.aj.get_highlights())
  File "/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump/aerojump.py", line 262, in get_highlights
    return self.highlights
AttributeError: 'AerojumpSpace' object has no attribute 'highlights'
Press ENTER or type command to continue
```
```
"Aerojump" [New File]
Error detected while processing CursorMoved Autocommands for "<buffer=13>":
E121: Undefined variable: b:original_commentstring
Press ENTER or type command to continue
```

**Comment by ripxorip** [comment]
Well :Aeorjump without any additional params won't work since its expecting which mode etc to run. Are you running from the latest commit on master? Trying to reproduce your error but I am not able to. Are you running the plugin on an empty buffer perhaps?

**Comment by ripxorip** [comment]
Empty buffer shall not cause any crashes anymore.

**Comment by ripxorip** [comment]
You have run :UpdateRemotePlugins first?

**Comment by henryoliver** [comment]
Yes,
```
remote/host: python3 host registered plugins ['aerojump', 'deoplete', 'far']
remote/host: generated rplugin manifest: /Users/henryoliver/.local/share/nvim/rplugin.vim
Press ENTER or type command to continue
```

And just ran `:PlugUpdate`
```
  7 - aerojump.nvim: Already up to date.                                                                                                              │   10     current,
```

I can't find anything on the doc that say how can you actually use Aerojump beside the vimrc mapping, here is my vimrc mapping:
```
" Aerojump
nmap <Leader>j <Plug>(AerojumpBolt)
nmap <Leader>aa <Plug>(AerojumpDefault)
```

And here is an screenshot when I use `aa (AerojumpDefault)` on my project file (buffer with a file on it)
![image](https://user-images.githubusercontent.com/870784/69457701-af176900-0d3b-11ea-94c7-4762b2354e1c.png)

`aa (AerojumpDefault)` and typing the word `React`
![image](https://user-images.githubusercontent.com/870784/69457933-32d15580-0d3c-11ea-912c-b6c5a8ccec3d.png)

```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
Error invoking '/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump:command:AerojumpDown' on channel 4 (python3-rplugin-host):
error caught in request handler '/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump:command:AerojumpDown [[], [3, 3]]':
Traceback (most recent call last):
  File "/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump/__init__.py", line 332, in AerojumpDown
    self.__update_highlights(self.aj.get_highlights())
  File "/Users/henryoliver/.config/nvim/plugged/aerojump.nvim/rplugin/python3/aerojump/aerojump.py", line 262, in get_highlights
    return self.highlights
AttributeError: 'Aerojump' object has no attribute 'highlights'
Press ENTER or type command to continue
```

Something weird is happening there, it may be a conflict with Deoplete autocomplete plugin.

**Comment by ripxorip** [comment]
Aha!! I think I know what the problem is. Can you try once more but without _any_ caps?

**Comment by ripxorip** [comment]
I wrote the plugin to be case insensitive so I think it gets confused when you start with a capital letter.

**Comment by henryoliver** [comment]
Ok, just updated everything, and did:

1. Open a very simple HTML file
![image](https://user-images.githubusercontent.com/870784/69479600-16c9c480-0dcd-11ea-9c28-7765ec91b7e9.png)

2. Pressed `<Leader>aa` and typed the word `meta`
![image](https://user-images.githubusercontent.com/870784/69479605-2ba65800-0dcd-11ea-89f6-c81efc16c343.png)

Nothing gets matched and when hit enter it just goes back to the buffer.

**Comment by henryoliver** [comment]
@ripxorip any idea about what could be the cause of this issue? Seems like the plugins tries to run into the input line instead of the current buffer.

**Comment by ripxorip** [comment]
Hi sorry for the delay. Are you by any chance running Mac/Linux? If so I would be interested to see if you could reproduce this behavior in an isolated environment such as Docker. That way I could easily debug it on my end. One other solution would be to provide you with an instrumented version of the plugin and sending me some logs. Cheers.

**Comment by henryoliver** [comment]
No problem @ripxorip, thanks for your help so far! I'm using macOS Catalina here. Could I send you some logs from the plugin? Is this possible? I think this may be a good start.

**Comment by dimroc** [comment]
Thanks for the plugin!
I also have the issue below and the inability to have case sensitive search. I have a suspicion that it's colliding with another plugin, either CoC tab completion or Semshi python.

This is when running on Redhat linux, not Mac OSX.

```
AttributeError: 'Aerojump' object has no attribute 'highlights'
```
