### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by delphinus** [philip-karlsson/aerojump.nvim#3]
Aerojump stucks and does not work with any key press.

Neovim v0.4.2
Python v3.7.4

* init.vim

   ```vim
   set runtimepath^=~/test/aerojump.nvim
   nmap # <Plug>(AerojumpDefault)
   ```

1. Run `nvim ~/neovim/src/nvim/eval.c`
2. Press `#` to launch.
3. It does not work with any key press.
4. Then move the middle of the screen with `M`.
5. Press `#` to launch.
6. Show errors.

<details>
<summary>the whole error</summary>

```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
Error invoking '/root/test/aerojump.nvim/rplugin/python3/aerojump:command:Aerojump' on channel 3 (python3-rplugin-host):
error caught in request handler '/root/test/aerojump.nvim/rplugin/python3/aerojump:command:Aerojump [['kbd', 'default'], [25, 25]]':
Traceback (most recent call last):
  File "/root/test/aerojump.nvim/rplugin/python3/aerojump/__init__.py", line 261, in Aerojump
    self.__draw()
  File "/root/test/aerojump.nvim/rplugin/python3/aerojump/__init__.py", line 99, in __draw
    self.__set_cursor_position(self.og_pos)
  File "/root/test/aerojump.nvim/rplugin/python3/aerojump/__init__.py", line 61, in __set_cursor_position
    self.nvim.current.window.cursor = pos
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/window.py", line 27, in cursor
    return self.request('nvim_win_set_cursor', pos)
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/common.py", line 51, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Cursor position outside buffer'
```
</details>

<details>
<summary>Reproducible Dockerfile</summary>

```Dockerfile
FROM python:3.7.4

RUN apt-get update && apt-get install -y \
    ninja-build gettext libtool libtool-bin autoconf automake cmake g++ \
    pkg-config unzip \
    git \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --single-branch --branch v0.4.2 https://github.com/neovim/neovim ~/neovim \
 && cd ~/neovim \
 && make CMAKE_BUILD_TYPE=Release \
 && make install

RUN mkdir -p ~/test \
 && git clone https://github.com/ripxorip/aerojump.nvim ~/test/aerojump.nvim

RUN pip3 install pynvim

RUN mkdir -p ~/.config/nvim
RUN echo '\
set runtimepath^=~/test/aerojump.nvim\n\
nmap # <Plug>(AerojumpDefault)\n\
' >> ~/.config/nvim/init.vim

RUN echo 'python3 -V' >> ~/.bashrc
RUN echo '( cd ~/test/aerojump.nvim && echo "aerojump.nvim: $(git rev-parse --short HEAD)" )' >> ~/.bashrc
RUN echo '( cd ~/neovim             && echo "neovim:        $(git rev-parse --short HEAD)" )' >> ~/.bashrc
RUN echo 'nvim --version' >> ~/.bashrc
RUN nvim +UpdateRemotePlugins +q
WORKDIR /root
ENTRYPOINT /bin/bash
```
</details>

[![asciicast](https://asciinema.org/a/272283.svg)](https://asciinema.org/a/272283)

**Comment by ripxorip** [comment]
Hmm.... Can´t really see why this can be happening unless something has changed in the plugin API to 0.4.2, thanks a lot for sharing the dockerfile, I will try to reproduce it at my end.

**Comment by ripxorip** [comment]
Just tested with 0.4.2 on my machine and it is working. Hopefully I can reproduce the error with your Dockerfile.

**Comment by ripxorip** [comment]
I was able to reproduce the error with your Dockerfile. It seems that the buffer references are unreliable, in order to workaround this I need to have another way of referencing the original buffer and making a deep copy of its input. I will keep you posted.

**Comment by ripxorip** [comment]
I think that i solved it now. I could get it to work with 41fd4736f9c4e3666272e63d39d2ea30f6dd58e2 using your Dockerfile. I would be really happy if you could verify. Thanks for helping out.

**Comment by delphinus** [comment]
Brilliant! It is fixed and works completely. Thx.
